services:
  discord-bot:
    build: 
      context: ./discord-bot
    container_name: discord_bot
    depends_on:
      - db
    env_file:
      - path: ./discord-bot/bot.env
        required: true
    volumes:
      - ./discord-bot/src:/app/
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./llm/data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_RUN=llama3

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres_db
    env_file:
      - path: ./database/db.env
        required: true
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    env_file: ./database/db.env
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
